import Navbar from "@/components/Navbar/Navbar";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { MovieProvider } from "@/components/ListMovie/MoviesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Movie DB",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body
                className={inter.className}
                style={{ display: 'grid', gridTemplateRows: '60px 1fr' }}
            >
                <MovieProvider>
                    <main>{children}</main>
                </MovieProvider>
            </body>
        </html>
    );
}
